Test script (random gibberish that is still correct according to the spec)
!@#$%^&*()_=+``~``~``

[

	Input.Offset := 0;
	Cappuccino := 4;
	Midpoint := 16;

]

	NewX := 0;
	y1 := 0;
	y2 := 0;

	four := 4;
	Coffee := Cappuccino;

{

	while (x * four > zero + (four + Input.Offset) ^ four ^ Cappuccino):
		NewX := x - Input.Offset;
		y1 := Cappuccino / NewX;
		if (!(x * y) > zero | y * four <= zero):
			y2 := NewX - Midpoint * atan(NewX / Midpoint);
		:
	:

	Coffee ^= four % y2 - y1 * NewX;

	y += y1 * y2;

}